services:
  - type: web
    name: todo-api
    runtime: dotnet
    repo: https://github.com/YOUR_GITHUB_REPO
    branch: main
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/ToDoListAPI.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
